
name: Pull Request on Push
on:
  push:
    branches-ignore:
      - main
      - dev
jobs:
  auto-pull-request:
    name: PullRequestAction
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
    steps:
      - name: PullRequestAction
        uses: vsoch/pull-request-action@1.0.19
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_BRANCH: 'main'
          PASS_IF_EXISTS: true
          PULL_REQUEST_TITLE: '${{env.BRANCH_NAME}}'
          PULL_REQUEST_BODY: '${{env.BRANCH_NAME}}'